# Generated by Django 4.1.7 on 2023-03-30 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Excursions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование экскурсии')),
                ('place', models.CharField(max_length=100, verbose_name='Место экскурсии')),
                ('time', models.CharField(max_length=100, verbose_name='Время экскурсии')),
                ('cost', models.IntegerField(verbose_name='Стоимость экскурcии')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование сервиса')),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование тура')),
                ('country', models.CharField(max_length=100, verbose_name='Страна')),
                ('time_live', models.CharField(max_length=100, verbose_name='Время проживания')),
                ('people', models.IntegerField(default=0, verbose_name='Количество человек')),
                ('hotel', models.CharField(choices=[('3', '★★★'), ('4', '★★★★'), ('5', '★★★★★')], max_length=100, verbose_name='Звёзд у отеля')),
                ('cost', models.IntegerField(default=0, verbose_name='Стоимость тура')),
                ('excursions', models.ManyToManyField(default=0, to='api.excursions', verbose_name='Экскурсии')),
                ('services', models.ManyToManyField(to='api.service', verbose_name='Cервис')),
            ],
        ),
        migrations.CreateModel(
            name='MyOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.IntegerField(default=0, verbose_name='Стоимость')),
                ('time', models.IntegerField(verbose_name='Время поездки(в часах)')),
                ('tours', models.ManyToManyField(to='api.tour', verbose_name='Тур')),
            ],
        ),
    ]
